stages:
    - compile
    - test
    - deploy

variables:
    MAVEN_CLI_OPTS: >-
        --batch-mode
        --errors
        --fail-at-end
        --show-version
        -DinstallAtEnd=true
        -DdeployAtEnd=true

before_script:
    - mvn ca.bkaw:paper-nms-maven-plugin:1.3.2:remap

compile:
    stage: compile
    script:
        - mvn clean install
    rules:
        - exists:
              - pom.xml
    artifacts:
        paths:
            - target/

test1:
    stage: test
    script:
        - mvn verify
    rules:
        - exists:
              - pom.xml

test2:
    stage: test
    script:
        - mvn verify
    rules:
        - exists:
              - pom.xml

deploy:
    stage: deploy
    script:
        - mvn $MAVEN_CLI_OPTS deploy
    rules:
        - exists:
              - target/
