package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class BlueClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.BLUE,
    a = "ꑞ",
    b = "ꑟ",
    c = "ꑠ",
    d = "ꑡ",
    e = "ꑢ",
    f = "ꑣ",
    g = "ꑤ",
    h = "ꑥ",
    i = "ꑯ",
    j = "ꑰ",
    k = "ꑱ",
    l = "ꑲ",
    m = "ꑺ",
    n = "ꑻ",
    o = "ꑼ",
    p = "ꑽ",
    q = "ꑾ",
    r = "ꑿ",
    s = "ꒀ",
    t = "ꒁ",
    u = "ꒂ",
    v = "ꒃ",
    w = "ꒄ",
    x = "ꒅ",
    y = "ꒆ",
    z = "ꒇ",
    zero = "ꒌ",
    one = "꒍",
    two = "꒎",
    three = "꒏",
    four = "꒐",
    five = "꒑",
    six = "꒒",
    seven = "꒓",
    eight = "꒔",
    nine = "꒕",
    spacerOne = "ꞛ",
    spacerTwo = "Ꞝ",
)