package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class BlueClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.BLUE,
    a = "Ꞡ",
    b = "ꞡ",
    c = "Ꞣ",
    d = "ꞣ",
    e = "Ꞥ",
    f = "ꞥ",
    g = "Ꞧ",
    h = "ꞧ",
    i = "Ꞩ",
    j = "ꞩ",
    k = "Ɦ",
    l = "Ɜ",
    m = "Ɡ",
    n = "Ɬ",
    o = "Ɪ",
    p = "ꞯ",
    q = "Ʞ",
    r = "Ʇ",
    s = "Ʝ",
    t = "Ꭓ",
    u = "Ꞵ",
    v = "ꞵ",
    w = "Ꞷ",
    x = "ꞷ",
    y = "Ꞹ",
    z = "ꞹ",
    zero = "Ꞻ",
    one = "ꞻ",
    two = "Ꞽ",
    three = "ꞽ",
    four = "Ꞿ",
    five = "ꞿ",
    six = "Ꟁ",
    seven = "ꟁ",
    eight = "Ꟃ",
    nine = "ꟃ",
    spacerOne = "ꞛ",
    spacerTwo = "Ꞝ",
)