package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class GreenClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.GREEN,
    a = "꒞",
    b = "꒟",
    c = "꒠",
    d = "꒡",
    e = "꒢",
    f = "꒣",
    g = "꒤",
    h = "꒥",
    i = "꒦",
    j = "꓄",
    k = "꓅",
    l = "꓆",
    m = "꓇",
    n = "꓈",
    o = "꓉",
    p = "꓊",
    q = "꓋",
    r = "꓌",
    s = "꓍",
    t = "꓎",
    u = "꓏",
    v = "ꓐ",
    w = "ꓑ",
    x = "ꓒ",
    y = "ꓓ",
    z = "ꓔ",
    zero = "ꓕ",
    one = "ꓖ",
    two = "ꓗ",
    three = "ꓘ",
    four = "ꓙ",
    five = "ꓚ",
    six = "ꓛ",
    seven = "ꓜ",
    eight = "ꓝ",
    nine = "ꓞ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
