package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class GreenClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.GREEN,
    a = "Ꝗ",
    b = "ꝗ",
    c = "Ꝙ",
    d = "ꝙ",
    e = "Ꝛ",
    f = "ꝛ",
    g = "Ꝝ",
    h = "ꝝ",
    i = "Ꝟ",
    j = "ꝟ",
    k = "Ꝡ",
    l = "ꝡ",
    m = "Ꝣ",
    n = "ꝣ",
    o = "Ꝥ",
    p = "ꝥ",
    q = "Ꝧ",
    r = "ꝧ",
    s = "Ꝩ",
    t = "ꝩ",
    u = "Ꝫ",
    v = "ꝫ",
    w = "Ꝭ",
    x = "ꝭ",
    y = "Ꝯ",
    z = "ꝯ",
    zero = "ꝰ",
    one = "ꝱ",
    two = "ꝲ",
    three = "ꝳ",
    four = "ꝴ",
    five = "ꝵ",
    six = "ꝶ",
    seven = "ꝷ",
    eight = "ꝸ",
    nine = "Ꝺ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)