package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class OrangeClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.ORANGE,
    a = "꟪",
    b = "꟫",
    c = "꟬",
    d = "꟭",
    e = "꟮",
    f = "꟯",
    g = "꟰",
    h = "꟱",
    i = "ꟲ",
    j = "ꟳ",
    k = "ꟴ",
    l = "Ꟶ",
    m = "ꟶ",
    n = "ꟷ",
    o = "ꟸ",
    p = "ꟹ",
    q = "ꟺ",
    r = "ꟻ",
    s = "ꟼ",
    t = "ꟽ",
    u = "ꟾ",
    v = "ꟿ",
    w = "ꠀ",
    x = "ꠁ",
    y = "ꠂ",
    z = "ꠃ",
    zero = "ꠄ",
    one = "ꠅ",
    two = "꠆",
    three = "ꠇ",
    four = "ꠈ",
    five = "ꠉ",
    six = "ꠊ",
    seven = "ꠋ",
    eight = "ꠌ",
    nine = "ꠍ",
    spacerOne = "꟥",
    spacerTwo = "꟦",
)