package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class OrangeClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.ORANGE,
    a = "ꗯ",
    b = "ꗰ",
    c = "ꗱ",
    d = "ꗲ",
    e = "ꗳ",
    f = "ꗴ",
    g = "ꗵ",
    h = "ꗶ",
    i = "ꗷ",
    j = "ꗸ",
    k = "ꗹ",
    l = "ꗺ",
    m = "ꗻ",
    n = "ꗼ",
    o = "ꗽ",
    p = "ꗾ",
    q = "ꗿ",
    r = "ꘀ",
    s = "ꘁ",
    t = "ꘂ",
    u = "ꘃ",
    v = "ꘄ",
    w = "ꘅ",
    x = "ꘆ",
    y = "ꘇ",
    z = "ꘈ",
    zero = "ꘉ",
    one = "ꘊ",
    two = "ꘋ",
    three = "ꘌ",
    four = "꘍",
    five = "꘎",
    six = "꘏",
    seven = "ꘐ",
    eight = "ꘑ",
    nine = "ꘒ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
