package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class PurpleClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.PURPLE,
    a = "꠴",
    b = "꠵",
    c = "꠶",
    d = "꠷",
    e = "꠸",
    f = "꠹",
    g = "꠺",
    h = "꠻",
    i = "꠼",
    j = "꠽",
    k = "꠾",
    l = "꠿",
    m = "ꡀ",
    n = "ꡁ",
    o = "ꡂ",
    p = "ꡃ",
    q = "ꡄ",
    r = "ꡅ",
    s = "ꡆ",
    t = "ꡇ",
    u = "ꡈ",
    v = "ꡉ",
    w = "ꡊ",
    x = "ꡋ",
    y = "ꡌ",
    z = "ꡍ",
    zero = "ꡎ",
    one = "ꡏ",
    two = "ꡐ",
    three = "ꡑ",
    four = "ꡒ",
    five = "ꡓ",
    six = "ꡔ",
    seven = "ꡕ",
    eight = "ꡖ",
    nine = "ꡗ",
    spacerOne = "꠯",
    spacerTwo = "꠰",
)