package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class PurpleClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.PURPLE,
    a = "꘼",
    b = "꘽",
    c = "꘾",
    d = "꘿",
    e = "Ꙁ",
    f = "ꙁ",
    g = "Ꙃ",
    h = "ꙃ",
    i = "Ꙅ",
    j = "ꙅ",
    k = "Ꙇ",
    l = "ꙇ",
    m = "Ꙉ",
    n = "ꙉ",
    o = "Ꙋ",
    p = "ꙋ",
    q = "Ꙍ",
    r = "ꙍ",
    s = "Ꙏ",
    t = "ꙏ",
    u = "Ꙑ",
    v = "ꙑ",
    w = "Ꙓ",
    x = "ꙓ",
    y = "Ꙕ",
    z = "ꙕ",
    zero = "Ꙗ",
    one = "ꙗ",
    two = "Ꙙ",
    three = "ꙙ",
    four = "Ꙛ",
    five = "ꙛ",
    six = "Ꙝ",
    seven = "ꙝ",
    eight = "Ꙟ",
    nine = "ꙟ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
