package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class RedClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.RED,
    a = "ꚉ",
    b = "Ꚋ",
    c = "ꚋ",
    d = "Ꚍ",
    e = "ꚍ",
    f = "Ꚏ",
    g = "ꚏ",
    h = "Ꚑ",
    i = "ꚑ",
    j = "Ꚓ",
    k = "ꚓ",
    l = "Ꚕ",
    m = "ꚕ",
    n = "Ꚗ",
    o = "ꚗ",
    p = "Ꚙ",
    q = "ꚙ",
    r = "Ꚛ",
    s = "ꚛ",
    t = "ꚜ",
    u = "ꚝ",
    v = "ꚞ",
    w = "ꚟ",
    x = "ꚠ",
    y = "ꚡ",
    z = "ꚢ",
    zero = "ꚣ",
    one = "ꚤ",
    two = "ꚥ",
    three = "ꚦ",
    four = "ꚧ",
    five = "ꚨ",
    six = "ꚩ",
    seven = "ꚪ",
    eight = "ꚫ",
    nine = "ꚬ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
