package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class RedClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.RED,
    a = "꡾",
    b = "꡿",
    c = "ꢀ",
    d = "ꢁ",
    e = "ꢂ",
    f = "ꢃ",
    g = "ꢄ",
    h = "ꢅ",
    i = "ꢆ",
    j = "ꢇ",
    k = "ꢈ",
    l = "ꢉ",
    m = "ꢊ",
    n = "ꢋ",
    o = "ꢌ",
    p = "ꢍ",
    q = "ꢎ",
    r = "ꢏ",
    s = "ꢐ",
    t = "ꢑ",
    u = "ꢒ",
    v = "ꢓ",
    w = "ꢔ",
    x = "ꢕ",
    y = "ꢖ",
    z = "ꢗ",
    zero = "ꢘ",
    one = "ꢙ",
    two = "ꢚ",
    three = "ꢛ",
    four = "ꢜ",
    five = "ꢝ",
    six = "ꢞ",
    seven = "ꢟ",
    eight = "ꢠ",
    nine = "ꢡ",
    spacerOne = "꡹",
    spacerTwo = "꡺",
)