package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class WhiteClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.WHITE,
    a = "ꛖ",
    b = "ꛗ",
    c = "ꛘ",
    d = "ꛙ",
    e = "ꛚ",
    f = "ꛛ",
    g = "ꛜ",
    h = "ꛝ",
    i = "ꛞ",
    j = "ꛟ",
    k = "ꛠ",
    l = "ꛡ",
    m = "ꛢ",
    n = "ꛣ",
    o = "ꛤ",
    p = "ꛥ",
    q = "ꛦ",
    r = "ꛧ",
    s = "ꛨ",
    t = "ꛩ",
    u = "ꛪ",
    v = "ꛫ",
    w = "ꛬ",
    x = "ꛭ",
    y = "ꛮ",
    z = "ꛯ",
    zero = "꛰",
    one = "꛱",
    two = "꛲",
    three = "꛳",
    four = "꛴",
    five = "꛵",
    six = "꛶",
    seven = "꜔",
    eight = "꜕",
    nine = "꜖",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
