package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class WhiteClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.WHITE,
    a = "꣈",
    b = "꣉",
    c = "꣊",
    d = "꣋",
    e = "꣌",
    f = "꣍",
    g = "꣎",
    h = "꣏",
    i = "꣐",
    j = "꣑",
    k = "꣒",
    l = "꣓",
    m = "꣔",
    n = "꣕",
    o = "꣖",
    p = "꣗",
    q = "꣘",
    r = "꣙",
    s = "꣚",
    t = "꣛",
    u = "꣜",
    v = "꣝",
    w = "꣞",
    x = "꣟",
    y = "꣠",
    z = "꣡",
    zero = "꣢",
    one = "꣣",
    two = "꣤",
    three = "꣥",
    four = "꣦",
    five = "꣧",
    six = "꣨",
    seven = "꣩",
    eight = "꣪",
    nine = "꣫",
    spacerOne = "ꣃ",
    spacerTwo = "꣄",
)