package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class YellowClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.YELLOW,
    a = "ꜣ",
    b = "Ꜥ",
    c = "ꜥ",
    d = "Ꜧ",
    e = "ꜧ",
    f = "Ꜩ",
    g = "ꜩ",
    h = "Ꜫ",
    i = "ꜫ",
    j = "Ꜭ",
    k = "ꜭ",
    l = "Ꜯ",
    m = "ꜯ",
    n = "ꜰ",
    o = "ꜱ",
    p = "Ꜳ",
    q = "ꜳ",
    r = "Ꜵ",
    s = "ꜵ",
    t = "Ꜷ",
    u = "ꜷ",
    v = "Ꜹ",
    w = "ꜹ",
    x = "Ꜻ",
    y = "ꜻ",
    z = "Ꜽ",
    zero = "ꜽ",
    one = "Ꜿ",
    two = "ꜿ",
    three = "Ꝁ",
    four = "ꝁ",
    five = "Ꝃ",
    six = "ꝃ",
    seven = "Ꝅ",
    eight = "ꝅ",
    nine = "Ꝇ",
    spacerOne = "ꝑ",
    spacerTwo = "Ꝓ",
)
