package dev.slne.clan.core.utils.tag.colors

import dev.slne.clan.api.tag.ClanTagColor
import dev.slne.clan.core.utils.tag.ClanTagColorMap

class YellowClanTagColorMap : ClanTagColorMap(
    clanTagColor = ClanTagColor.YELLOW,
    a = "ꤒ",
    b = "ꤓ",
    c = "ꤔ",
    d = "ꤕ",
    e = "ꤖ",
    f = "ꤗ",
    g = "ꤘ",
    h = "ꤙ",
    i = "ꤚ",
    j = "ꤛ",
    k = "ꤜ",
    l = "ꤝ",
    m = "ꤞ",
    n = "ꤟ",
    o = "ꤠ",
    p = "ꤡ",
    q = "ꤢ",
    r = "ꤣ",
    s = "ꤤ",
    t = "ꤥ",
    u = "ꤦ",
    v = "ꤧ",
    w = "ꤨ",
    x = "ꤩ",
    y = "ꤪ",
    z = "꤫",
    zero = "꤬",
    one = "꤭",
    two = "꤮",
    three = "꤯",
    four = "ꤰ",
    five = "ꤱ",
    six = "ꤲ",
    seven = "ꤳ",
    eight = "ꤴ",
    nine = "ꤵ",
    spacerOne = "ꤍ",
    spacerTwo = "ꤎ",
)