name: SurfEssentials
version: '1.0.1-SNAPSHOT'
main: dev.slne.surf.essentials.SurfEssentials
description: '"Insert description here"'
api-version: '1.19'
bootstrapper: dev.slne.surf.essentials.SurfEssentialsBootstrap
loader: dev.slne.surf.essentials.SurfEssentialsLoader
authors: ['twisti', 'SLNE Dev Team']
website: 'https://git.slne.dev/surf/surf-essentials'