name: '${name}'
version: '${project.version}'
main: ${project.mainClass}
description: '${project.description}'
api-version: '${project.apiVersion}'
bootstrapper: ${project.bootstrapper}
loader: ${project.loader}
authors: [${project.authors}]
website: '${project.url}'

dependencies:
  - name: CoreProtect
    required: false
    bootstrap: false

load-after:
  - name: CoreProtect
    bootstrap: false