name: SurfEssentials
version: '1.0-SNAPSHOT'
main: dev.slne.surf.essentials.SurfEssentials
description: '"Insert description here"'
api-version: '1.19'
bootstrapper: dev.slne.surf.essentials.SurfEssentialsBootstrap
loader: dev.slne.surf.essentials.SurfEssentialsLoader
has-open-classloader: true
authors: ['twisti', 'SLNE Dev Team']
website: 'https://git.slne.dev/surf/surf-essentials'

########################################################################################################################
#                                                 Dependencies                                                         #
########################################################################################################################
dependencies:
  - name: ProtocolLib
    required: true
    bootstrap: false


########################################################################################################################
#                                                     Load-order                                                       #
########################################################################################################################
load-after:
  - name: ProtocolLib
    bootstrap: false