########################################################################################################################
#                 The project now generates this file automatically when it compiles using annotations                 #
########################################################################################################################


permissions:
  surf.essentials:
    children:
      surf.essentials.commands.suicide:
        description: Allows you to suicide
      surf.essentials.commands.suicide.others:
        description: Allows you to suicide other players
  surf.teleport.announce:
    description: Anounce to you if someone has teleported

  surf.essentials.announce.op:
    description: Anounce to you op changes
