name: SurfEssentials
version: '${project.version}'
main: dev.slne.surf.essentials.SurfEssentials
api-version: 1.19
depend: [SurfAPI]
author:

commands:
  fly:
    usage: /fly
    description: Allow you to fly!
    permission:
      fly.use:
    permission-message: You don´t have permission to fly!

  heal:
    usage: /heal
    description: Heals you instantly!
    permission:
      heal.use:
    permission-message: You don´t have permission to heal yourself!

  godmode:
    usage: /godmode
    description: Makes you god!
    permission:
      godmode.use:
    permission-message: You don´t have permission to make yourself god!
    aliases: [gommemode]

  feed:
    usage: /feed
    description: Feeds you instantly!
    permission:
      feed.use:
    permission-message: You don't have permission to feed yourself!

  repair:
    usage: /repair
    description: Repairs everything in your main hand!
    permission:
      repair.use:
    permission-message: You don't have permission to repair!

  adventure:
    usage: /adventure <Player name>
    description: Change your gamemode or from another online player to creative!
    permission:
      gamemode.adventure.change
    permission-message: You don't have permission to change your gamemode!

  creative:
    usage: /creative <Player name>
    description: Change your gamemode or from another online player to creative!
    permission:
      gamemode.creative.change
    permission-message: You don't have permission to change your gamemode!

  spectator:
    usage: /spectator <Player name>
    description: Change your gamemode or from another online player to creative!
    permission:
      gamemode.spectator.change
    permission-message: You don't have permission to change your gamemode!

  survival:
    usage: /survival <Player name>
    description: Change your gamemode or from another online player to creative!
    permission:
      gamemode.survival.change
    permission-message: You don't have permission to change your gamemode!

  tptop:
    usage: /tptop
    description: Teleports you to the highest block at your location.
    permission:
      tp.top.use
    permission-message: You don't have permission to teleport!
    aliases: [teleporttop, teletop]

  tpall:
    usage: /tpall
    description: Teleports all online players to you.
    permission:
      tp.all.use
    permission-message: You don't have permission to teleport others!

  info:
    usage: /info <player>
    description: Display information about a player!
    aliases: [information]
    permission:
      info.use
    permission-message: You don't have permission to view information about other players!

  rain:
    usage: /rain
    description: Sets the weather to rain.
    aliases: [wrain, weatherrain, essentialsrain, erain]
    permission:
      rain.weather.change
    permission-message: You don't have permission to change the weather!

  rule:
    usage: /rule <player>
    description: Displays the rules of the server to a player.
    aliases: [rules, serverrule, serverrules]
    permission:
      rule.use
    permission-message: You don't have permission to display the rules!

  time:
    usage: /time <time>
    description: Sets the time to day/evening/night/midnight
    permission:
      time.use:
    permission-message: You don't have permission to change the time!
